version: '2.4'
services:
  postgres_dev:
    container_name: 'postgres-dev'
    image: 'postgres:14.1-alpine'
    env_file:
      - ../../.env
    ports:
      - '54320:5432'
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data:
